branch-defaults:
  master:
    environment: pos-api-dev
global:
  application_name: pos-api
  default_ec2_keyname: nick-peters
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Node.js
  default_region: us-west-2
  profile: null
  sc: git
